GenData.out : GenData.cpp GenData.h Librairie.cpp Librairie.h
	g++ GenData.cpp -o GenData.out

CreateMozaique.out : CreateMozaique.cpp CreateMozaique.h Librairie.cpp Librairie.h
	g++ CreateMozaique.cpp -o CreateMozaique.out